tap "homebrew/bundle"
brew "antigen"
brew "mackup"
brew "mas"
cask "1password"
cask "1password-cli"
cask "git-credential-manager"
cask "setapp"
mas "1Password for Safari", id: 1569813296
mas "Xcode", id: 497799835
